In [1]:
!pip install numpy

Requirement already satisfied: numpy in /opt/anaconda3/lib/python3.13/site-packages (2.3.5)

In [2]:
!pip install pandas

Requirement already satisfied: pandas in /opt/anaconda3/lib/python3.13/site-packages (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in /opt/anaconda3/lib/python3.13/site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/anaconda3/lib/python3.13/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /opt/anaconda3/lib/python3.13/site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /opt/anaconda3/lib/python3.13/site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in /opt/anaconda3/lib/python3.13/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [4]:
import sys
print(sys.executable)

/usr/local/bin/python3

In [1]:
import sys
!{sys.executable} -m pip install pandas numpy

Requirement already satisfied: pandas in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (3.0.1)
Requirement already satisfied: numpy in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (2.4.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/evansrumao/Library/Python/3.13/lib/python/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /Users/evansrumao/Library/Python/3.13/lib/python/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 24.3.1 -> 26.0.1
[notice] To update, run: pip3 install --upgrade pip

In [2]:
import numpy as np
import pandas as pd

In [3]:
labels=['a','b','c']
my_data=[10,20,30]
arr=np.array(my_data)
d={'a':10,'b':20,'c':30}

In [5]:
pd.Series(data=my_data)

0    10
1    20
2    30
dtype: int64

In [7]:
pd.Series(data=my_data,index=labels)

a    10
b    20
c    30
dtype: int64

In [9]:
pd.Series(d)

a    10
b    20
c    30
dtype: int64

DataFrames using Pandas

In [10]:
data = {
    'Name': ['John', 'Anna', 'Peter', 'Linda'],
    'Age': [28, 34, 29, 42],
    'City': ['New York', 'Paris', 'Berlin', 'London'],
    'Salary': [65000, 70000, 62000, 85000]
}
df = pd.DataFrame(data)

In [11]:
df.head()

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [12]:
data_list = [
    ['John', 28, 'New York', 65000],
    ['Anna', 34, 'Paris', 70000],
    ['Peter', 29, 'Berlin', 62000],
    ['Linda', 42, 'London', 85000]
]
df2 = pd.DataFrame(data_list)
columns = ["Name","Age","City","Salary"]
df2 = pd.DataFrame(data_list,columns =columns)
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

selection and indexing of columns

In [14]:
df2[[ "Name","Age" ]]

    Name  Age
0   John   28
1   Anna   34
2  Peter   29
3  Linda   42

In [15]:
df2["Name"]

0     John
1     Anna
2    Peter
3    Linda
Name: Name, dtype: str

Creating a new coloumn

In [21]:
df["designation"]=["Data Scientist","Data Analyst","Data Engineer","ML Engineer"]
df

    Name  Age      City  Salary     designation
0   John   28  New York   65000  Data Scientist
1   Anna   34     Paris   70000    Data Analyst
2  Peter   29    Berlin   62000   Data Engineer
3  Linda   42    London   85000     ML Engineer

In [22]:
df.drop("designation",axis = 1)

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [23]:
df

    Name  Age      City  Salary     designation
0   John   28  New York   65000  Data Scientist
1   Anna   34     Paris   70000    Data Analyst
2  Peter   29    Berlin   62000   Data Engineer
3  Linda   42    London   85000     ML Engineer

In [24]:
df.drop("designation",axis = 1,inplace = True)
df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [25]:
df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [26]:
df.drop(["Age","City"],axis=1,inplace=True)
df

    Name  Salary
0   John   65000
1   Anna   70000
2  Peter   62000
3  Linda   85000

In [27]:
df

    Name  Salary
0   John   65000
1   Anna   70000
2  Peter   62000
3  Linda   85000

In [28]:
df["Age"]=[28, 34, 29, 42]
df["City"]=['New York', 'Paris', 'Berlin', 'London']
df

    Name  Salary  Age      City
0   John   65000   28  New York
1   Anna   70000   34     Paris
2  Peter   62000   29    Berlin
3  Linda   85000   42    London

In [30]:
df.drop(0,axis = 0,inplace = True) #drop the first row inplace is used to make the change permanent
df

    Name  Salary  Age    City
1   Anna   70000   34   Paris
2  Peter   62000   29  Berlin
3  Linda   85000   42  London

Selecting a Row

In [ ]:
df2.loc[[0,1]]

   Name  Age      City  Salary
0  John   28  New York   65000
1  Anna   34     Paris   70000

In [ ]:
df2.iloc[3] #iloc is used to access rows by their integer position, while loc is used to access rows by their label. In this case, df2.iloc[3] will return the fourth row of the DataFrame, which corresponds to the data for "Linda".

Name       Linda
Age           42
City      London
Salary     85000
Name: 3, dtype: object

Selecting subsets of rows and coloumns

In [ ]:
df.loc[[1,2]][["City","Salary"]] #loc is used to access rows and columns by their labels. In this case, df.loc[[1,2]] will return the rows with labels 1 and 2, which correspond to "Anna" and "Peter". Then, [["City","Salary"]] is used to select only the "City" and "Salary" columns from those rows.

     City  Salary
1   Paris   70000
2  Berlin   62000

In [42]:
df.loc[[2,3]][["Name","Age"]]

    Name  Age
2  Peter   29
3  Linda   42

Conditional Selection

In [44]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [43]:
df2[df2["Age"] > 30]

    Name  Age    City  Salary
1   Anna   34   Paris   70000
3  Linda   42  London   85000

In [45]:
df2[(df2["Age"] > 30) & (df2["City"] == 'Paris')]

   Name  Age   City  Salary
1  Anna   34  Paris   70000