In [1]:
!pip install numpy

Requirement already satisfied: numpy in /opt/anaconda3/lib/python3.13/site-packages (2.3.5)

In [2]:
import numpy as np
import pandas as pd

In [3]:
data = {
    'Category': ['A', 'B', 'A', 'B', 'A', 'B', 'A', 'B'],
    'Store': ['S1', 'S1', 'S2', 'S2', 'S1', 'S2', 'S2', 'S1'],
    'Sales': [100, 200, 150, 250, 120, 180, 200, 300],
    'Quantity': [10, 15, 12, 18, 8, 20, 15, 25],
    'Date': pd.date_range('2023-01-01', periods=8)
}
df = pd.DataFrame(data)

In [4]:
df

  Category Store  Sales  Quantity       Date
0        A    S1    100        10 2023-01-01
1        B    S1    200        15 2023-01-02
2        A    S2    150        12 2023-01-03
3        B    S2    250        18 2023-01-04
4        A    S1    120         8 2023-01-05
5        B    S2    180        20 2023-01-06
6        A    S2    200        15 2023-01-07
7        B    S1    300        25 2023-01-08

# Group by Category and calculate the sum of Sales

In [8]:
cat=df.groupby('Category')
for name, group in cat:
    print(f"Category: {name}")
    print(group)
    print("\n")

Category: A
  Category Store  Sales  Quantity       Date
0        A    S1    100        10 2023-01-01
2        A    S2    150        12 2023-01-03
4        A    S1    120         8 2023-01-05
6        A    S2    200        15 2023-01-07


Category: B
  Category Store  Sales  Quantity       Date
1        B    S1    200        15 2023-01-02
3        B    S2    250        18 2023-01-04
5        B    S2    180        20 2023-01-06
7        B    S1    300        25 2023-01-08

In [ ]:
cat['Sales'].sum() # Grouping by 'Category' and summing the 'Sales' column

Category
A    570
B    930
Name: Sales, dtype: int64

In [12]:
cat=df.groupby('Store')['Sales'].sum() # Grouping by 'Store' and summing the 'Sales' column
cat

Store
S1    720
S2    780
Name: Sales, dtype: int64

In [13]:
# Group by multiple columns
# Group by Category and Store
cat = df.groupby(['Category','Store'])['Sales'].sum()
cat

Category  Store
A         S1       220
          S2       350
B         S1       500
          S2       430
Name: Sales, dtype: int64

Aggregation

In [ ]:
df['Sales'].mean() # Calculate the mean sales for each category

np.float64(187.5)

In [ ]:
df['Sales'].agg(['sum', 'mean', 'min', 'max', 'count', 'std', 'median']) # Calculate multiple aggregate functions for the 'Sales' column

sum       1500.000000
mean       187.500000
min        100.000000
max        300.000000
count        8.000000
std         66.062741
median     190.000000
Name: Sales, dtype: float64

pivot Tables

In [16]:
data = {
    'Date': pd.date_range('2023-01-01', periods=20),
    'Product': ['A', 'B', 'C', 'D'] * 5,
    'Region': ['East', 'West', 'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West',
               'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West', 'North', 'South'],
    'Sales': np.random.randint(100, 1000, 20),
    'Units': np.random.randint(10, 100, 20),
    'Rep': ['John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary',
            'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice']
}

df = pd.DataFrame(data)

In [17]:
df

         Date Product Region  Sales  Units    Rep
0  2023-01-01       A   East    362     57   John
1  2023-01-02       B   West    226     81   Mary
2  2023-01-03       C  North    692     51    Bob
3  2023-01-04       D  South    648     95  Alice
4  2023-01-05       A   East    471     49   John
5  2023-01-06       B   West    193     57   Mary
6  2023-01-07       C  North    507     56    Bob
7  2023-01-08       D  South    948     57  Alice
8  2023-01-09       A   East    313     13   John
9  2023-01-10       B   West    212     68   Mary
10 2023-01-11       C  North    869     28    Bob
11 2023-01-12       D  South    876     46  Alice
12 2023-01-13       A   East    899     87   John
13 2023-01-14       B   West    972     24   Mary
14 2023-01-15       C  North    525     61    Bob
15 2023-01-16       D  South    573     80  Alice
16 2023-01-17       A   East    493     97   John
17 2023-01-18       B   West    526     64   Mary
18 2023-01-19       C  North    862     70    Bob
19 2023-01-20       D  South    916     28  Alice

In [19]:
pd.pivot_table(df,values='Sales',index='Product',columns='Region') # Create a pivot table to summarize sales by product and region

Region    East  North  South   West
Product
A        507.6    NaN    NaN    NaN
B          NaN    NaN    NaN  425.8
C          NaN  691.0    NaN    NaN
D          NaN    NaN  792.2    NaN

In [20]:
pd.pivot_table(df,values='Sales',index='Product',columns='Region',aggfunc='median') # Create a pivot table to summarize median sales by product and region

Region    East  North  South   West
Product
A        471.0    NaN    NaN    NaN
B          NaN    NaN    NaN  226.0
C          NaN  692.0    NaN    NaN
D          NaN    NaN  876.0    NaN

In [21]:
pivot2 = pd.pivot_table(df, values=['Sales', 'Units'], index='Region', columns='Product')
pivot2

         Sales                      Units
Product      A      B      C      D     A     B     C     D
Region
East     507.6    NaN    NaN    NaN  60.6   NaN   NaN   NaN
North      NaN    NaN  691.0    NaN   NaN   NaN  53.2   NaN
South      NaN    NaN    NaN  792.2   NaN   NaN   NaN  61.2
West       NaN  425.8    NaN    NaN   NaN  58.8   NaN   NaN

In [ ]:
pd.crosstab(df['Region'],df['Product']) # Create a crosstab to show the frequency of products sold in each region

Product  A  B  C  D
Region
East     5  0  0  0
North    0  0  5  0
South    0  0  0  5
West     0  5  0  0

DataFrames Basic Operations

In [23]:
df1 = pd.DataFrame({
    'A': [1, 2, 3, 4, 5],
    'B': [10, 20, 30, 40, 50],
    'C': [100, 200, 300, 400, 500]
})

In [24]:
df1

   A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500

In [25]:
df1.shape # Get the shape of the DataFrame (number of rows and columns)

(5, 3)

In [26]:
df1.columns # Get the column names of the DataFrame

Index(['A', 'B', 'C'], dtype='str')

In [27]:
df1.info() # Get a concise summary of the DataFrame, including data types and non-null counts

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       5 non-null      int64
 1   B       5 non-null      int64
 2   C       5 non-null      int64
dtypes: int64(3)
memory usage: 252.0 bytes

In [28]:
df1.describe() # Get summary statistics for the DataFrame

              A          B           C
count  5.000000   5.000000    5.000000
mean   3.000000  30.000000  300.000000
std    1.581139  15.811388  158.113883
min    1.000000  10.000000  100.000000
25%    2.000000  20.000000  200.000000
50%    3.000000  30.000000  300.000000
75%    4.000000  40.000000  400.000000
max    5.000000  50.000000  500.000000

In [29]:
df1['A'] + 10 # Add 10 to each value in column 'A'

0    11
1    12
2    13
3    14
4    15
Name: A, dtype: int64

In [30]:
df1['D'] = df1["B"].apply(lambda x : x**2) # Create a new column 'D' by applying a lambda function to column 'B' that squares each value

In [31]:
df1

   A   B    C     D
0  1  10  100   100
1  2  20  200   400
2  3  30  300   900
3  4  40  400  1600
4  5  50  500  2500

In [34]:
def Square(x):
    return x**2

In [35]:
df1['B']=df1['B'].apply(Square) # Apply the Square function to each value in column 'B'

In [36]:
df1

   A     B    C     D
0  1   100  100   100
1  2   400  200   400
2  3   900  300   900
3  4  1600  400  1600
4  5  2500  500  2500